### PR TITLE
check is exist extension before add profile

### PR DESCRIPTION
**Pull request by odevyatkov**
check is exist extension before add profile

### CODE REVIEW

**Comment by munrocket** [comment]
Hello @odevyatkov thank you for PR! Seems that I am already check for existing in this line `if (ext[fn]) ext[fn]`. Probably variable `ext` should be named as `getExt`. Can you explain what you see in this example? https://munrocket.github.io/gl-bench/examples/instanced-arrays.html

**Comment by odevyatkov** [comment]
gl.getExtension return `null` if extension not allow or not exist ( https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/getExtension ).
In this case after run `let ext = fn.apply(gl, arguments);` variable `ext` equal `null` and as result error `Cannot read property of null` here `ext[fn]`.

**Comment by odevyatkov** [comment]
i caught error on run this code line https://github.com/uber/luma.gl/blob/75ab19e5b40da73c92880545c08ed0ec0cc28c26/modules/webgl/src/classes/framebuffer.js#L596

**Comment by munrocket** [comment]
Interesting extension, I never heard about `WEBGL.draw_buffers`, only `WEBGL_draw_buffers`. We should add this string in array of supported extensions in gl-bench?

**Comment by munrocket** [comment]
Do you attach `gl-bench` to context before luma.gl?

**Comment by munrocket** [comment]
Ok seems that we need change `apply` to `bind`, because right now this PR not idiomatic enough. But it was a bug in code, yep.

**Comment by odevyatkov** [comment]
> Interesting extension, I never heard about `WEBGL.draw_buffers`, only `WEBGL_draw_buffers`. We should add this string in array of supported extensions in gl-bench?

Unfortunately i am not author of this package - so i dont know why they use `WEBGL.draw_buffers` ( may be bug

**Comment by munrocket** [comment]
This PR looks right, thanks @odevyatkov.

**Comment by odevyatkov** [comment]
> This PR looks right, thanks @odevyatkov.

thanks you for great package

**Comment by munrocket** [comment]
In 5 minutes travis will publish new version in NPM.

**Pull request merged**
